### ISSUE TITLE
add key `--show-logs`

### ISSUE THREAD

**Issue by dekhtyarev** [2gis/k8s-handle#10]
#### Вывод логов
> Доступна только для Job (а точнее для [Non-parallel Jobs](https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/#writing-a-job-spec))

После завершения работы пода, созданного джобой, выведет его логи на экран.
Завершением работы пода считается переход из состояния Running в состояниe Succeeded/Failed/Unknown
Рантайм режим временно не доступен из-за бага: https://github.com/kubernetes-client/python/issues/199
```bash
k8s-handle deploy --section <section_name> --config <config-name> --show-logs
```
При необходимости указать кол-во строк
```bash
--tail-lines <tail-lines> (по умолчанию выведет все логи с момента создания пода)
```

PS Для Parallel Jobs можно пока не реализовывать. Запросов на них ещё не было

**Comment by rvadim** [comment]
Why its P0? It's just logging improvement.

**Comment by dekhtyarev** [comment]
Some pipelines will be broken, who used this feature in internal k8s-handle relese:
```
$ k8s-handle deploy --section run-at-ci --sync-mode --show-logs
usage: k8s-handle [-h] {deploy,destroy} ...
k8s-handle: error: unrecognized arguments: --show-logs
ERROR: Job failed: exit code 1
```

But this may be P1.. I change

**Comment by dekhtyarev** [comment]
Don't forget 2+ containers in POD support
