### ISSUE TITLE
Add to_yaml filter to template processor

### ISSUE THREAD

**Issue by rvadim** [2gis/k8s-handle#115]
Standard Ansible template syntax has to_yaml and to_nice_yaml filters https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html#filters-for-formatting-data
This filter will be very helpful for k8s-handle cases like insert `tolerations` and `affinity` to resulting resource.

**Comment by dekhtyarev** [comment]
Released in [0.10.0](https://github.com/2gis/k8s-handle/releases/tag/0.10.0)
