### ISSUE TITLE
k8s-handle diff support

### ISSUE THREAD

**Issue by sepich** [2gis/k8s-handle#121]
Hello,
How hard is to add `kubectl diff` functionality right into k8s-handle?
It is handy to have a test for Merge Request actually showing what would be changed in Cluster after all templates are rendered etc.
Right now we are using something like:
```
k8s-handle render -s section

kubectl config set-credentials user --token="$K8S_TOKEN"
kubectl config set-cluster cluster --server=https://k8s --insecure-skip-tls-verify=true
kubectl config set-context context --cluster=cluster --user=user
kubectl config use-context context

kubectl diff -n namespace -R -f /tmp/k8s-handle
```
While running steps in docker, this requires container with both k8s-handle and kubectl - which complicates stuff.
Advantage to have diff in python is that it's format would be easier to customize (drop unnecessary fields etc)

Another command where knowledge about objects in the Cluster could be useful is `deploy`.
Because for new users all these logs looks scary:
`INFO:k8s_handle.k8s.provisioner:Deployment "prometheus" already exists, replace it`
Why do you replace the object if it does not changed? For example `kubectl apply` shows if object was actually changed or not. Would be great to show diff on `deploy` too, or skip objects which has zero diff.

What do you think?

**Comment by rvadim** [comment]
Hi, thank you for report.
It's currently unavailable due to https://github.com/kubernetes-client/python/issues/1117
