### ISSUE TITLE
Add support for variables that contain dashes

### ISSUE THREAD

**Issue by nvarscar** [2gis/k8s-handle#129]
Currently, if a variable (or one of the child properties of a variable) in config.yaml contains a dash symbol, the deployment automatically fails.
It would be very useful to at least allow child properties to contain dashes, which are natively supported by the yaml format.

Use case: I'm building a template that would have different variable values based on region name, and I would have to remove the dash symbol from the region variable that comes from the deployment pipeline.

Error example:
```
ERROR:k8s_handle:RuntimeError: Variable names should never include dashes, check your vars, please: us-central1, us-east1
```

**Comment by rvadim** [comment]
Hi @nvarscar! Thank you for your report. I will check the ability to solve this.

**Comment by rvadim** [comment]
@dekhtyarev @furiousassault any additional suggestions on this?

**Comment by furiousassault** [comment]
I don't remember exactly the reason why this limitation appeared. Can anyone remind, @rvadim, @seleznev?

**Comment by seleznev** [comment]
> why this limitation appeared

AFAIK, if you put something like `{{ some-variable-name }}` in Jinja2 template, you will receive a very unclear error message. So this limitation was added to prevent confusing error messages.

**Comment by nvarscar** [comment]
My use case revolves around being able to select a value from a map:
```
---
region: us-east1
regionMap:
  us-east1: do this
  us-west1: do that
```
and then use `{{ regionMap[region] }}` to pick a proper choice for each particular region.

**Comment by rvadim** [comment]
@nvarscar your case in the tests now:
https://github.com/2gis/k8s-handle/pull/130/files#diff-736ae61165a40dc46e06fac92616d2383f8099ec8511763e0a55eb396065f406R114

**Comment by rvadim** [comment]
@nvarscar Please test 0.11.1 release

**Comment by nvarscar** [comment]
@rvadim it works! Thanks for such a quick response and action, much appreciated.
