### ISSUE TITLE
Unit tests do not pass without setting env. variables

### ISSUE THREAD

**Issue by furiousassault** [2gis/k8s-handle#26]
В проекте присутстуют юнит-тесты, которые, имхо, по-хорошему должны запускаться при клонировании репозитория и локально, без дополнительных манипуляций.

Вариант решения: добавить объявление и удаление env переменных в setUp / tearDown методы классов-тесткейсов, оставив в tox.ini только log level.

**Comment by rvadim** [comment]
Что значит без дополнительных манипуляций? Без установки tox? И почему должны?

**Comment by furiousassault** [comment]
Без установки произвольных переменных окружения, чтобы найти которые нужно отсмотреть тесты и/или tox-скрипт. И поставить tox, да. 

Предположим, я просто клонирую репозиторий и хочу нажать `python3 -m unittest`, тесты не проходят. Разве и не должны? Юниты тестируют код, поэтому, на мой взгляд, было бы чуть более правильно их инициализацию внутри самих тест-кейсов/тест-модуля и обеспечить.
