### ISSUE TITLE
Create and push only 'latest' TAG into hub.docker.com

### ISSUE THREAD

**Issue by dekhtyarev** [2gis/k8s-handle#29]
Now, we push all TAGs into [hub.docker.com](https://hub.docker.com/r/2gis/k8s-handle/tags/). 

Pick yourself up and stop.

**Comment by FreakyGranny** [comment]
is actual?

**Comment by dekhtyarev** [comment]
Yes

**Comment by dekhtyarev** [comment]
Этот тикет о том, что на hub.docker.com пушатся все собранные в travis-ci образы. 

Нужно оставить, чтобы туда пушились только образы из `master` ветки

**Comment by dekhtyarev** [comment]
Реализовано на стороне интеграции hub.docker.com и github в рамках нашего репозитория. 

Теперь так:
![image](https://user-images.githubusercontent.com/17539237/46066325-98f53380-c19e-11e8-9c40-a125fdfbb33a.png)

FYI: @rvadim @FreakyGranny @furiousassault
