### ISSUE TITLE
Separate templating and deploying processes

### ISSUE THREAD

**Issue by LMnet** [2gis/k8s-handle#43]
At the current moment in k8s-handle `deploy` command  consists of two phases:
1. Templating. In this phase, jinja templates combine with `config.yaml` and produce k8s config files.
2. Actual deploy. In this phase, k8s-handle use generated k8s config files and start the deploy process.

I think it would be good to have an option to run this phases separately. These processes look pretty independent between themselves. And optional templating could give a possibility to use other template technics (not everybody are happy with jinja + `config.yaml` approach) while preserving convenience from the simple k8s-handle deploy logic.

Actually, I already can run the first phase without the actual deploy with `--dry-run` flag. But it looks like a side effect, not an intention.

As far as I understand, separation of actual deployment needs some extra work. Here are some problems I could see:
1. k8s-handle requires `config.yaml` file with the `common` section. If actual deploy would be separated from the templating, k8s-handle should be able to work without `config.yaml` at all. Honestly, requiring `common` section feels very synthetic for me, even apart from the current task.
2. Deploy requires some special keys in the `config.yaml`. I'm talking about `k8s_namespace`, `k8s_master_uri`, `k8s_token` and `k8s_ca_base64`. k8s-handle should be able to get these variables from the CLI parameters.

I can suggest two ways of implementation:
1. Add two new commands: `template` and `deploy-only` (bad names, only for example). These commands will have different parameters. And the current `deploy` command will combine both these commands. This approach looks cleaner for me, and I think strategically this is a more reliable plan. But `--dry-run` flag should be deprecated in that case, because this flag will duplicate the `template` command.
2. Add some more flags for the current `deploy` command. I think something like `--no-templating` could work. But I'm afraid of increasing complexity of flag combinations.

**Comment by rvadim** [comment]
Actually, this feature in my plan for next steps. I think we create 2 phases: build and provision. Thank you for your feature request.

**Comment by dekhtyarev** [comment]
Release [0.5.0](https://github.com/2gis/k8s-handle/releases/tag/0.5.0)
